"$id": "https://open-broker.org/se/Mortgage/schema/definitions/Application"
"$schema": "http://json-schema.org/draft-07/schema#"

application:
  type: object
  additionalProperties: false
  required:
    - applicant
    - propertyAddress
    - refinancingProperty
  properties:
    refinancingProperty:
      '$ref': '#/definitions/OwnedProperty'
      "$linkVal": "OwnedProperty"
      title: The property that should be refinanced
    propertyAddress:
      '$ref': '#/definitions/PropertyAddress'
      "$linkVal": "PropertyAddress"
      title: The address of the property which should be refinanced
    extensions:
      '$ref': '#/definitions/ExtensionPoint'
      "$linkVal": "ExtensionPoint"
      title: "Custom, vendor-specific extensions to the schema"
    applicant:
      "$ref": "#/definitions/applicant"
      "$linkVal": "applicant"
      title: "Applicant"
      description: "The primary applicant to the loan"
    coApplicant:
      "$ref": "#/definitions/applicant"
      "$linkVal": "applicant"
      title: "Co-applicant"
      description: "A secondary applicant for the loan, if any."
    existingLoans:
      type: array
      title: "Information about existing loans relevant to the applicant"
      items:
        "$ref": "#/definitions/ExistingLoan"
        "$linkVal": "ExistingLoan"
    ownedProperties:
      type: array
      title: Properties owned by the applicant(s)
      description: |
        Any currently owned real-estate property owned by the applicant(s),
        either owned together or individually. The property that is being
        refinanced ("refinancingProperty") should not be included.
      items:
        '$ref': '#/definitions/OwnedProperty'
        "$linkVal": "OwnedProperty"