"$id": "https://open-broker.org/se/Mortgage/schema/definitions/Application"
"$schema": "http://json-schema.org/draft-07/schema#"

application:
  type: object
  additionalProperties: false
  required:
    - loanAmount
    - termMonths
    - applicant
    - propertyAddress
  properties:
    loanAmount:
      type: integer
      title: "Amount to borrow"
      description: "The amount that the customer wishes to borrow"
      minimum: 1
      examples:
        - 2300000
    termMonths:
      type: integer
      title: 'Number of monthly terms'
      description: "The number 1-month terms that the applicant desires to pay off the loan over"
      minimum: 1
      examples:
        - 240
    propertyAddress:
      '$ref': '#/definitions/PropertyAddress'
      "$linkVal": "PropertyAddress"
      title: The address of the property which should be refinanced
    extensions:
      '$ref': '#/definitions/ExtensionPoint'
      "$linkVal": "ExtensionPoint"
      title: "Custom, vendor-specific extensions to the schema"
    applicant:
      "$ref": "#/definitions/applicant"
      "$linkVal": "applicant"
      title: "Applicant"
      description: "The primary applicant to the loan"
    coApplicant:
      "$ref": "#/definitions/applicant"
      "$linkVal": "applicant"
      title: "Co-applicant"
      description: "A secondary applicant for the loan, if any."
    existingLoans:
      type: array
      title: "Information about existing loans relevant to the applicant"
      items:
        "$ref": "#/definitions/ExistingLoan"
        "$linkVal": "ExistingLoan"