version: 2.1

executors:
  schema-context:
    docker:
      - image: mantono/alpine-yaml-json
    working_directory: ~/workdir

jobs:
  convert:
    executor: schema-context
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: se/Mortgage/v0
          command: .circleci/yaml2json.sh se/Mortgage/v0
      - run:
          name: no/Mortgage/v0
          command: .circleci/yaml2json.sh no/Mortgage/v0
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - json

  validate:
    executor: schema-context
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: se/Mortgage/v0
          command: ajv compile -s /tmp/workspace/json/se/Mortgage/v0/schema.json
      - run:
          name: no/Mortgage/v0
          command: ajv compile -s /tmp/workspace/json/no/Mortgage/v0/schema.json

  test:
    executor: schema-context
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: no/Mortgage/v0
          command: |
            cd ~/workdir &&
            .circleci/test_examples.sh no/Mortgage/v0

workflows:
  version: 2.1

  schema:
    jobs:
      - convert
      - validate:
          requires:
            - convert
      - test:
          requires:
            - validate
