version: 2.1

executors:
  schema-context:
    docker:
      - image: mantono/alpine-yaml-json
    working_directory: ~/workdir

jobs:
  convert:
    executor: schema-context
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: no/Mortgage/v0
          command: .circleci/yaml2json.sh no/Mortgage/v0
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - json


  validate:
    executor: schema-context
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cd /tmp/workspace/json 
      - run:
          name: no/Mortgage/v0
          command: ajv compile -s no/Mortgage/v0/schema.json

  test:
    executor: schema-context
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cd /tmp/workspace/json
      - run:
          name: no/Mortgage/v0
          command: ./test_examples.sh no/Mortgage/v0

workflows:
  version: 2.1

  schema:
    jobs:
      - convert
      - validate:
          requires:
            - convert